[tool.poetry]
name = "maya fey"
version = "0.6.1"
description = ""
authors = ["Shine-Light <3120815902@qq.com>"]

[[tool.poetry.source]]
name = "aliyun"
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[tool.poetry.dependencies]
python = "^3.9"
aiocache = "^0.11.1"
aiocqhttp = "^1.4.2"
aiofiles = "^0.8.0"
aiohttp = "^3.8.1"
emoji = "^1.7.0"
fontTools = "^4.33.0"
httpx = "^0.23.0"
imageio = "^2.14.1"
jieba = "^0.42.1"
Jinja2 = "^3.0.3"
loguru = "^0.6.0"
Markdown = "^3.3.6"
nonebot2 = "^2.0.0-rc.1"
nonebot-plugin-apscheduler = "^0.2.0"
nonebot-adapter-onebot = "^2.1.5"
Pillow = "^9.1.1"
playwright = "^1.17.2"
pydantic = "^1.9.0"
pyee="^8.2.2"
PyMySQL = "^0.9.3"
requests = "^2.27.1"
tencentcloud_sdk_python = "^3.0.595"
typing_extensions = "^4.2.0"
ujson = "^5.1.0"
wordcloud = "^1.8.1"
msgpack = "^1.0.3"
cryptography = "^36.0.1"

[tool.poetry.dev-dependencies]


[tool.nonebot]
plugins = []
plugin_dirs = ["content/plugins", "content/plugin_private",
            "Api", "hook"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
